name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: docker://kivy/buildozer:latest
      with:
        args: android debug
      env:
        # Buildozer'ın işini yapması için gerekli izinler
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
